### ISSUE TITLE
[Documentation] Add ORM diagram to README

### ISSUE THREAD

**Issue by therzka** [ProgramEquity/amplify#354]
It would be useful to have a visual that demonstrates our database models, their attributes, and how they relate to one another

https://github.com/ProgramEquity/amplify/wiki/Data-Structures

**Comment by ipc103** [comment]
A Mermaid [Class Diagram](https://github.com/mermaidjs/mermaidjs.github.io/blob/master/classDiagram.md) might work well for this.

**Comment by ahn-nath** [comment]
Hello, @ipc103. 

I would like you to provide feedback on my progress with the Mermaid Class Diagram I have generated when you have time, so I can create a PR for this issue and keep updating it from there.  Also, I do not know if I should also tag @therzka for future reviews or if you will be the only mentor that will help with this issue. 

### This is the result of my work (current version):
```mermaid
classDiagram
    campaigns "1" -- "0...n" letter_versions
    sent_letters "0...n" --"1" letter_versions
    constituents "1" -- "0...n" sent_letters
    stripe_payments_table "1" -- "1" sent_letters
    class campaigns{
      +int id 
      +string organization
      +string name
      +enum cause
      +enum type
      +getCampaign()
      +getCampaigns()
      
    }
    class letter_versions{
      +int id
      +int template_id
      +enum office_division
      +string state
      +string country
      +integer CampaignID
      +getLetterVersions()
    
    }
    class sent_letters{
      +int id
      +int letter_version_id
      +int constituent_id
      +int request_id
      +timestampt requested_at
      +string rep_name
      +string rep_address 
      +createLetters()
      
    }

    class constituents{
        +int letters_sent
        +boolean user_agreement
        +updates
        +string street_address
        +string city
        +string state
        +string zipcode
    }

    class stripe_payments_table{
        +int id
        +timestamp day 
        +int amount
        +string currency
        +int source_id
        +string type
        +createTransaction()
    }
```
Edit live with: https://mermaid.live/ 

### Assumptions:
**I have assumed the following to complete the diagram:**
[Stripe payments table](https://github.com/ProgramEquity/amplify/wiki/Data-Structures#stripe-payments-table):  I have assumed them because the author does not clearly define the two fields.
- source_id: this is the id of the letter sent in the [sent_letters table](https://github.com/ProgramEquity/amplify/wiki/Data-Structures#sent_letters-table).
- id: the unique identifier of the table.

**Associations:**
I have established the following multiplicity associations:
- A campaign can have 0 or more letter versions. A letter version can only have one.
`    campaigns "1" --> "0...n" letter_versions`
- A letter version can have 0 or n sent letters. A sent letter can only have one letter version.
`letter_versions "1" --> "0...n" sent_letters`
- A constituent/representative can have 0 or more letters sent to them. A sent letter can only correspond to one constituent.  
   ` constituents "1" --> "0...n" sent_letters`
- stripe_payments_table "1" --> "1" sent_letters. The payment of a sent letter can only be made or linked to one sent letter.
- All properties are public in the class (I have only used the "+" symbol).
- I have inferred some methods from the files in the ``server/routes/api` and `the server/db/models` folders of the project/repository. 


### Questions and concerns:

- There are data structures that are not explicitly described in the DB folder that helps recreate the tables/models. I do not know if I should keep the [data structures page](https://github.com/ProgramEquity/amplify/wiki/Data-Structures#sent_letters-table) as my main reference or [the current version of the project](https://github.com/ProgramEquity/amplify/tree/main/server/db). 
- The "Updates" field of the [constituents table](https://github.com/ProgramEquity/amplify/wiki/Data-Structures#constituents-table) has no description or data type, it is hard for me to assume it. 

### Sources I used as a reference:
- [Include diagrams in your Markdown files with Mermaid | The GitHub Blog](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/)
- [Mermaid.js](https://mermaid-js.github.io/mermaid/#/)

**Comment by ipc103** [comment]
@ahn-nath Great work on this - I think this is super helpful is looking great. Hope you enjoyed working with the mermaid syntax - how was it? 

> There are data structures that are not explicitly described in the DB folder that helps recreate the tables/models. I do not know if I should keep the [data structures page](https://github.com/ProgramEquity/amplify/wiki/Data-Structures#sent_letters-table) as my main reference or [the current version of the project](https://github.com/ProgramEquity/amplify/tree/main/server/db).

Good question - ideally this would always mirror the up to date version of the schema, but I don't think it's necessary to include seeder classes, etc. Are there new tables/models that aren't reflected in the data structures page? 

At some point, it would be nice if we could auto-generate the diagram based on the schema, but we can worry about that at a later point in time 😄 

> The "Updates" field of the [constituents table](https://github.com/ProgramEquity/amplify/wiki/Data-Structures#constituents-table) has no description or data type, it is hard for me to assume it.

Me too - also confused as to where that's referenced 😄 @therzka any chance you have more info on what that refers to? 

One additional piece of feedback - the associations between the tables are a bit hard to decipher with with `1, 0..n` notation. Instead, this might make more sense to convert to an ERD diagram: https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram?id=syntax

Another option would be to use the "Association" marker between the different classes: https://mermaid-js.github.io/mermaid/#/classDiagram?id=defining-relationship

**Comment by ipc103** [comment]
>  if I make a pull request, should it be to update the data structures page to add that diagram? Or do I update another file?

I'm not super opinionated, but the top of the `Data Structures` page makes sense to me 👍

**Comment by ahn-nath** [comment]
> @ahn-nath Great work on this - I think this is super helpful is looking great. Hope you enjoyed working with the mermaid syntax - how was it?

Not bad. The syntax was easy to catch because I am familiar with Markdown, and they have a live editor to test your lines.

> Good question - ideally this would always mirror the up to date version of the schema, but I don't think it's necessary to include seeder classes, etc. Are there new tables/models that aren't reflected in the data structures page?

No. The opposite is true. There are models that are not reflected in the repository but are in the data structures page. These are the models I see under the db folder:
![image](https://user-images.githubusercontent.com/67247850/200734155-c9d13739-5e24-4182-b731-61116a02a9b5.png)

**Comment by ahn-nath** [comment]
> > if I make a pull request, should it be to update the data structures page to add that diagram? Or do I update another file?
> 
> I'm not super opinionated, but the top of the `Data Structures` page makes sense to me 👍

I just realized I do not need to make a pull request because it is a Wiki page.

**Comment by ahn-nath** [comment]
```mermaid
classDiagram
    campaigns "1" --> "0...n" letter_versions: can have
    sent_letters "0...n" -->"1" letter_versions: correspond to
    constituents "1"--> "0...n" sent_letters:receives
    stripe_payments_table "1" --> "1" sent_letters: is linked to
    class campaigns{
      +int id 
      +string organization
      +string name
      +enum cause
      +enum type
      +getCampaign()
      +getCampaigns()
      
    }
    class letter_versions{
      +int id
      +int template_id
      +enum office_division
      +string state
      +string country
      +integer CampaignID
      +getLetterVersions()
    
    }
    class sent_letters{
      +int id
      +int letter_version_id
      +int constituent_id
      +int request_id
      +timestampt requested_at
      +string rep_name
      +string rep_address 
      +createLetters()
      
    }

    class constituents{
        +int letters_sent
        +boolean user_agreement
        +updates
        +string street_address
        +string city
        +string state
        +string zipcode
    }

    class stripe_payments_table{
        +int id
        +timestamp day 
        +int amount
        +string currency
        +int source_id
        +string type
        +createTransaction()
    }
```

I drew a directed association and added labels/markers to describe the nature of the relation between the two classes. Let me know if it's better/clearer.

**Comment by ipc103** [comment]
> No. The opposite is true. There are models that are not reflected in the repository but are in the data structures page. These are the models I see under the db folder: ![image](https://user-images.githubusercontent.com/67247850/200734155-c9d13739-5e24-4182-b731-61116a02a9b5.png)

👍 - thanks for clarifying. My assumption is that the docs are referring to the actual DB schema and that each table may not have a corresponding model. I think that this documentation should reflect the DB schema. We can confirm if my assumption is correct and proceed accordingly 😄

**Comment by ahn-nath** [comment]
> 👍 - thanks for clarifying. My assumption is that the docs are referring to the actual DB schema and that each table may not have a corresponding model. I think that this documentation should reflect the DB schema. We can confirm if my assumption is correct and proceed accordingly 😄
@manishapriya94 @paramsiddharth 

Hello, how could I verify this with Codespaces? Thank you.

**Comment by paramsiddharth** [comment]
> > 👍 - thanks for clarifying. My assumption is that the docs are referring to the actual DB schema and that each table may not have a corresponding model. I think that this documentation should reflect the DB schema. We can confirm if my assumption is correct and proceed accordingly 😄
> 
> @manishapriya94 @paramsiddharth
> 
> Hello, how could I verify this with Codespaces? Thank you.

@ahn-nath You can use `psql`, the PostgreSQL CLI, to connect to the database using the command-line and check the schema. :) That's ONE way. You can also examine the migrations in the repository.

**Comment by ahn-nath** [comment]
> @ahn-nath You can use `psql`, the PostgreSQL CLI, to connect to the database using the command-line and check the schema. :) That's ONE way. You can also examine the migrations in the repository.

Could you please elaborate more on this please? I have used PostgreSQL CLI and PgAdmin, and as far as my interactions with the tool can tell, to establish a remote connection, I will need some connection details that look like this for a local connection: 
![image](https://user-images.githubusercontent.com/67247850/200980795-43bb3375-d47a-4ff5-94aa-920bcf7354c1.png)

I am specifically interested in connecting to the database Codespaces uses and view the tables (if I am not mistaken, it must be a remote connection to the database of the project that is on Heroku). Second, I already looked at the migrations, but they are not necessarily an accurate representation of the current status of the database. 

I will move forward with this task, but if you believe it is necessary for me to visualize them myself, please provide more guidance on how to do so. Thanks.

**Comment by ahn-nath** [comment]
> 👍 - thanks for clarifying. My assumption is that the docs are referring to the actual DB schema and that each table may not have a corresponding model. I think that this documentation should reflect the DB schema. We can confirm if my assumption is correct and proceed accordingly 😄

I have checked the migrations, and they are, not completely in sync with the data structures described in the page. I will make the changes in accordance to the migrations version and place it at the top of the Wiki page.

I have discussed this with other mentors and after some thought, I believe the most efficient way to move forward with this task is “to have a visual that demonstrates the **database models described in the Wiki page this issue was initially linked to**”. Furthermore, I believe, as you do, that the documentation should reflect the DB schema, but @manishapriya94 mentioned that we need to wait for the author to come back and help us move forward, probably by making sure is up-to-date with the project status. Then, if more changes are needed, because the data structures are changed, we can make sure to update the diagram with code. 


Let me know what you think, @ipc103.

**Comment by ipc103** [comment]
> I have checked the migrations, and they are, not completely in sync with the data structures described on the page. I will make the changes in accordance with the migrations version and place it at the top of the Wiki page.
> 
> I have discussed this with other mentors and after some thought, I believe the most efficient way to move forward with this task is “to have a visual that demonstrates the database models described in the Wiki page this issue was initially linked to”. Furthermore, I believe, as you do, that the documentation should reflect the DB schema, but [@manishapriya94](https://github.com/manishapriya94) mentioned that we need to wait for the author to come back and help us move forward, probably by making sure is up-to-date with the project status. Then, if more changes are needed, because the data structures are changed, we can make sure to update the diagram with code. 
> 
> Let me know what you think, [@ipc103](https://github.com/ipc103).

Thanks - that sounds like a reasonable plan to me! 👍

**Comment by paramsiddharth** [comment]
> > @ahn-nath You can use `psql`, the PostgreSQL CLI, to connect to the database using the command-line and check the schema. :) That's ONE way. You can also examine the migrations in the repository.
> 
> Could you please elaborate more on this please? I have used PostgreSQL CLI and PgAdmin, and as far as my interactions with the tool can tell, to establish a remote connection, I will need some connection details that look like this for a local connection: ![image](https://user-images.githubusercontent.com/67247850/200980795-43bb3375-d47a-4ff5-94aa-920bcf7354c1.png)
> 
> I am specifically interested in connecting to the database Codespaces uses and view the tables (if I am not mistaken, it must be a remote connection to the database of the project that is on Heroku). Second, I already looked at the migrations, but they are not necessarily an accurate representation of the current status of the database.
> 
> I will move forward with this task, but if you believe it is necessary for me to visualize them myself, please provide more guidance on how to do so. Thanks.

@ahn-nath There's no need to connect to the database remotely using a local CLI, because I believe you can use the `psql` CLI from within the command-line inside Codespaces itself. :) If you have any problems in doing that, feel free to let me know. The database URI and the password should be present within environment variables.

**Comment by ahn-nath** [comment]
@manishapriya94 

Is there any update on this issue?
