### ISSUE TITLE
[Documentation] Move Devs + QA discussion comments into separate wiki pages

### ISSUE THREAD

**Issue by therzka** [ProgramEquity/amplify#357]
[This discussion post](https://github.com/ProgramEquity/amplify/discussions/62) currently contains user stories and walkthroughs of each of Amplify's features, but it's not discoverable.  This information should be restructured and moved to the wiki (a page for each feature or a big page with a table of contents/headers) 

for example, the features listed at the top of the discussion should each be their own page (with the contents of the discussion comment they link to) 

![image](https://user-images.githubusercontent.com/7219923/219177699-8f148509-94f8-4333-96ac-c71ecb89337d.png)

ex) the contents of [this comment](https://github.com/ProgramEquity/amplify/discussions/62#discussioncomment-2128538) should exist as a wiki page under Features > Browse causes

The issues linked in tables at the bottom of these comments are out of date - we should either not include the in the wiki pages, or create labels for each feature and link to a PR search that filters by the given label for each feature

**Comment by rsensenig** [comment]
Hi @therzka - Upon reviewing the discussion post and the wiki, I added some things to the wiki from the discussion post to fill in knowledge gaps. Here's a breakdown of the updates I made:

* added the "Context" video from the discussion post to an App-Demo.md file that I created
* added the details of the user journey, and Amplify's features to a User-Journey.md file that I created
* updated the Background.md file to User-Background.md so that it's more clear from the title that the file is talking about users, and clarified some of the language within that file to differentiate between constituents and advocacy groups
* nested User Background and User Journey underneath a header of "Users" in the sidebar

I made these changes in a  clone of the wiki in a personal repo I created here: https://github.com/rsensenig/amplify-wiki.

If you could review and merge (or approve me merging) if these changes look good to you that would be much appreciated. Thanks so much!

**Comment by rsensenig** [comment]
Hi @therzka - According to our discussion, and the update to the issue that you made above, I updated the wiki so that the features from the Dev discussion are nested under "Features" on the sidebar of the wiki with a page dedicated to each feature. I've created labels named after the features, which can be seen here: https://github.com/ProgramEquity/amplify/labels. I've attached some of these labels to existing issues, and linked the search of this label at the bottom of the feature page.

Please let me know if I should make any further edits, or if we're all set to close out this issue. Thanks!

**Comment by therzka** [comment]
wiki looks fantastic, thank you @rsensenig! Thanks for making the followup issue as well, I might create a separate one for categorizing issues using the paragraph your new issue

🚀
