### ISSUE TITLE
Bug: createAddress not working

### ISSUE THREAD

**Issue by mahrsbar** [ProgramEquity/amplify#91]
## Expected Behaviour
We recently combined the addressVerification and createAddress as one api call. However, the new createAddress call does not seem to be working. I would expect createAddress api in [lob.js](https://github.com/ProgramEquity/amplify/blob/main/server/routes/api/lob.js) to send me an address_id as a response if I send an address to it. @teakopp We were working on this in the hackathon but don't think we found the problem. 

## Current Behaviour
I keep receiving a "Something failed" error instead of an address_id. I have tried different variations of the address and ensured that the address is correct through addressVerification. 

**createAddress failing**
<img width="1006" alt="Screen Shot 2022-02-25 at 3 04 06 PM" src="https://user-images.githubusercontent.com/66452376/155809327-d734ec94-c360-43d9-b6e3-b0e3c440b35a.png">

**addressVerification working - shows its not an issue with the address**
<img width="1001" alt="Screen Shot 2022-02-25 at 3 07 10 PM" src="https://user-images.githubusercontent.com/66452376/155809680-57bc4fff-ffa9-4e05-afee-563e6ddeb98c.png">

**Comment by teakopp** [comment]
Hey @mahrsbar 

I think I may have found the problem. The variable `zipCode` was being checked but not used, because call was using at zip. So every address would have seemed to have been missing a zip code, but passed the check. I think this is the result of a check from `/verifyAddress` accidentally being omitted. We'll add some more descriptive messages in the future to say exactly what is failing. This [PR](https://github.com/ProgramEquity/amplify/pull/120) should fix it 🤞🏻

**Comment by mahrsbar** [comment]
@JamesMGreene Would the most updated api link be `https://amplify-app-production.herokuapp.com/api`or `https://murmuring-headland-63935.herokuapp.com/api ` if I'm testing on Postman?

**Comment by JamesMGreene** [comment]
@mahrsbar `https://amplify-app-production.herokuapp.com/api` has the latest. 👍🏻 

(The other needs to be shutdown soon.)

**Comment by manishapriya94** [comment]
Hi folks, @teakopp and I looked into this and the error is most likely happening as CORS was removed. Heres a demo on how to use it today cc: @anishasthana @aneelac22 

Uploading onboarding codespaces.mov…

**Comment by ankitagrawal98** [comment]
Access to XMLHttpRequest at 'https://amplify-app-production.herokuapp.com/api/lob/addressVerification' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

^^ Is the current issue Mahrs is running into.

**Comment by ankitagrawal98** [comment]
All of LOB's error codes:

GENERIC
bad_request - 422: an invalid request was made. See error message for details.
conflict - 409/422: this operation would leave data in a conflicted state.
feature_limit_reached - 403: the account has reached its resource limit and requires upgrading to add more.
internal_server_error - 500: an error has occured on Lob's servers. Please try request again.
invalid - 422: an invalid request was made. See error message for details.
not_deletable - 422: an attempt was made to delete a resource, but the resource cannot be deleted.
not_found - 404: the requested resource was not found.
request_timeout - 408: the request took too long. Please try again.
service_unavailable - 503: the Lob servers are temporarily unavailable. Please try agian.
unrecognized_endpoint - 404: the requested endpoint doesn't exist.
unsupported_lob_version - 422: an unsupported Lob API version was requested.

ADVANCED
address_length_exceeds_limit - 422: the sum of to.address_line1 and to.address_line2 cannot surpass 50 characters.
bank_account_already_verified - 422: the bank account has already been verified.
bank_error - 422: there's an issue with the bank account.
custom_envelope_inventory_depleted - 422: custom envelope inventory is depleted, and more will need to be ordered.
deleted_bank_account - 404: checks cannot be created with a deleted bank account.
failed_deliverability_strictness - 422: the to address doesn't meet strictness requirements. See [Account Settings](https://dashboard.lob.com/#/settings/account) to configure strictness.
file_pages_below_min - 422: not enough pages.
file_pages_exceed_max - 422: too many pages.
file_size_exceeds_limit - 422: the file size is too large. See description for details.
foreign_return_address - 422: the from address must be a US address.
inconsistent_page_dimensions - 422: all pages of the input file must have the same dimensions.
invalid_bank_account - 422: the provided bank routing number is invalid.
invalid_bank_account_verification - 422: verification amounts do not match.
invalid_check_international - 422: checks cannot be sent internationally.
invalid_country_covid - 422: the postal service in the specified country is currently unable to process the request due to COVID-19 restrictions.
invalid_file - 422: the file is invalid.
invalid_file_dimensions - 422: file dimensions are incorrect for the selected mail type.
invalid_file_download_time - 422: file download from remote server took too long.
invalid_file_url - 422: the file URL when creating a resource is invalid.
invalid_image_dpi - 422: DPI must be at least 300.
invalid_international_feature - 422: the specified product cannot be sent to the destination.
invalid_perforation_return_envelope - 422: both return_envelope and perforation must be used together.
invalid_template_html - 422: the provided HTML is invalid.
merge_variable_required - 422: a required merge variable is missing.
merge_variable_whitespace - 422: merge variable names cannot contain whitespace.
payment_method_unverified - 401: you must have a verified bank account or credit card to submit live requests.
pdf_encrypted - 422: an encrypted PDF was provided.
special_characters_restricted - 422: cannot use special characters for merge variable names.
unembedded_fonts - 422: the provided PDF contains non-standard unembedded fonts. See description for details.

AUTHENTICATION
email_required - 401: account must have a verified email address before creating live resources.
invalid_api_key - 401/403: the API key is invalid.
publishable_key_not_allowed - 403: the requested operation needs a secret key, not a publishable key. See [API Keys](https://docs.lob.com/#section/API-Keys) for more information.
rate_limit_exceeded - 429: requests were sent too quickly and must be slowed down.
unauthorized - 401: the request isn't authorized.
unauthorized_token - 401: token isn't authorized

**Comment by manishapriya94** [comment]
Potential fix: https://github.com/ProgramEquity/amplify/issues/213
